### ISSUE TITLE
Specify dependency update strategy for Gumbo HTML5 parser

### ISSUE THREAD

**Issue by fulldecent** [rubys/nokogumbo#135]
Please specify this project's policy (in the README) of how updates to Gumbo HTML5 parser will be evaluated and included in this project.

---

Motivation: our project depends (3 levels deep) on this project and certain HTML errors are not being caught. We will want to work to solve the issue but we would also like to know that each of these layers can implement this fix when it is available. Having a documented update policy will help.

**Comment by stevecheckoway** [comment]
Project policies are @rubys's call. That said, I try to fix bugs that are reported, time permitting.

**Comment by fulldecent** [comment]
It appears that Gumbo is not actively maintained.

Source: https://github.com/google/gumbo-parser/branches, see age of branches

Will this project consider to depend on a fork of the official Google branch? If so, what would be the policy of choosing an eligible fork?

**Comment by stevecheckoway** [comment]
Nokogumbo hasn't used that version of Gumbo since version 2. See the [CHANGELOG](https://github.com/rubys/nokogumbo/blob/master/CHANGELOG.md#200---2018-10-04). The code lives [here](https://github.com/rubys/nokogumbo/tree/master/gumbo-parser/src).

@craigbarnes put in a bunch of work to fix issues with Gumbo and provide improvements. I've updated it to match the HTML living standard as that standard changes (although, it could easily have fallen behind again), fix crashes and other bugs, as well as improved the test suite to cover most of the code paths in the library.

**Comment by fulldecent** [comment]
Aha! Okay, so maybe this can resolve the underlying issue here...

https://github.com/rubys/nokogumbo/pull/140

**Comment by stevecheckoway** [comment]
It appears that I misunderstood your original question. I thought you were asking about our version. Thanks for the PR, that's definitely an improvement.

Is that change to the README sufficient for you, or do you need more specific policy text?

**Comment by fulldecent** [comment]
I am trying to fix Gumbo.

Originally I thought that this project was only relying on Google Gumbo. At that point my question was: if I fix Gumbo then does that get used here?

Later I learned that this project now maintains its own Gumbo. So it is obvious that my Gumbo fixes can come here and then be integrated into Nokogumbo. It is also obvious that this project does not need to sync to Google because Google Gumbo is dead.

Now I understand how Gumbo fixes get in here. So I'm set. But #140 helps communicate this to the world, so that resolves the issue.

**Comment by stevecheckoway** [comment]
Great! PRs and bug reports welcome for any Gumbo issues you find.
