### ISSUE TITLE
Installation fails on Mac OS 10.11.6

### ISSUE THREAD

**Issue by TIny-Hacker** [rubys/nokogumbo#176]
I'm trying to install nokogumbo on my Mac. I followed the installation instructions and didn't get any errors till I ran `rake gem`. After that I got a very long list of errors. (Crash log below) I have installed nokogiri (latest version).
[ruby_2021-04-20-094354.log](https://github.com/rubys/nokogumbo/files/6344022/ruby_2021-04-20-094354.log)

**Comment by flavorjones** [comment]
Hi, @TIny-Hacker. Thanks for opening this issue and sorry that you're having problems. I'll try to help.

I need to ask for a bit more information in order to understand the state of your system:

- What's the output of `gem env`?
- If you're using bundler, what's the output of `bundler env` in that project directory?
- Can you re-install nokogiri and nokogumbo (but first uninstall them, please!) and share the output that you see?
- What command are you running when you see this crash?

Thanks in advance for helping us understand!

**Comment by TIny-Hacker** [comment]
I'm sorry to bother you but in the end I set it up on Ubuntu and it worked fine after all. Thanks for helping anyway!

**Comment by stevecheckoway** [comment]
Very strange! It's an illegal instruction in `xmlFindCharEncodingHandler`. That strikes me as a function pointer that got corrupted. But hard to say why that would be.
