### ISSUE TITLE
Tag the releases

### ISSUE THREAD

**Issue by balasankarc** [rubys/nokogumbo#18]
RubyGems report that this gem is now in the version 1.3.0. Can you please tag the releases?

**Comment by rubys** [comment]
Done: https://github.com/rubys/nokogumbo/releases/tag/v1.3.0

**Comment by balasankarc** [comment]
I am sorry, but the folder gumbo-parser in the tagged version is empty and doesnot contain the header files that are needed for building (like gumbo.h). Can you check that also?

**Comment by rubys** [comment]
I simply followed the GitHub instructions for [Creating Releases](https://help.github.com/articles/creating-releases/).  I also tried building a gem with the test files, and got the following error that I don't understand:

```
Gem::InvalidSpecificationException: ["test-nokogumbo.rb"] are not files
```

Since I seem to be merely poking around in the dark, would it be possible for you to construct a pull request that meets your needs?

**Comment by balasankarc** [comment]
Can you share me the gemspec file you used for building the gem?

**Comment by balasankarc** [comment]
About the submodules missing, it is not your problem. Github doesn't include submodules in releases and I believe they have no plan to implement it in near future. :( 
Let me try to figure out what is the issue with creating a Gem file.

**Comment by rubys** [comment]
Can you try the following instructions?  They build the gemspec: https://github.com/rubys/nokogumbo/#installation

**Comment by balasankarc** [comment]
I don't know how, but I succeeded in building a Gem including the tests. Have mailed it to you. Please check if it is fine.

**Comment by rubys** [comment]
"I don't know how" <- that concerns me.  I would prefer something reproducible.

It is also worth noting that if the gumbo parser is available it will be used directly instead of being compiled into nokogumbo.  In the case of Debian, perhaps it would be better to have nokogumbo depend on gumbo-parser?

**Comment by balasankarc** [comment]
I just added the file test-nokogumbo to the Rakefile list for building gem

task 'gem' => 'test'
SPEC = Gem::Specification.new do |gem|
  gem.name = 'nokogumbo'
  gem.version = '1.3.0'
  gem.email = 'rubys@intertwingly.net'
  gem.homepage = 'https://github.com/rubys/nokogumbo/#readme'
  gem.summary = 'Nokogiri interface to the Gumbo HTML5 parser'
  gem.extensions = 'ext/nokogumboc/extconf.rb'
  gem.author = 'Sam Ruby'
  gem.add_dependency 'nokogiri'
  gem.license = 'Apache 2.0'
  gem.description = %q(
    Nokogumbo allows a Ruby program to invoke the Gumbo HTML5 parser and
    access the result as a Nokogiri parsed document.).strip.gsub(/\s+/, ' ')
  gem.files = SOURCES + FileList[
    'lib/nokogumbo.rb',
    'LICENSE.txt',
    'README.md',
    'gumbo-parser/src/*',
    'gumbo-parser/visualc/include/*',
    'test-nokogumbo.rb'
  ]
end

What I meant by "I don't know how" was I don't know why it didn't work for you. I know why it worked for me. :smile: 

About Debian, I think that would be enough. But, as long as libgumbo doesn't reach Debian, we just have to wait. Let me ping the guy who filed ITP on that one.
