### ISSUE TITLE
Gentoo (and Centos?) build re-broken

### ISSUE THREAD

**Issue by nyarly** [rubys/nokogumbo#40]
In #38, there's a reversion of a fix for Gentoo linking - I see that the argument is that making the linkage work makes sense "upstream", but the problem is that e.g. nokogumbo is a dep of sanitize, which we use in Rails apps - through Bundler. Making the Gentoo ebuild of nokogumbo work doesn't help for deploying a Rails app to Gentoo.

@svoop suggested in discussion in the pull request that users could set flags themselves - if there's a flag to pass during gem install or via bundle config, that'd be a fine, but I haven't been able to determine what those flags would be.

**Comment by svoop** [comment]
@nyarly I can't speak for Centos since I'm all Gentoo. How do you install Ruby on your Gentoo-Box? Via ebuild, manually or with RVM, ruby-install etc?

**Comment by nyarly** [comment]
I use ebuild. Either eselect or chruby to switch.

**Comment by svoop** [comment]
Been there! Using Rubies from Portage and then installing gems via Bundler is an epic source of frustration. I've switched to installing Rubies with [ruby-install](https://github.com/postmodern/ruby-install) and things are going much smoother ever since. Your mileage may vary.

> Either eselect or chruby to switch.

eselect is a good illustration: It will only switch gem bins for gems installed by Portage. Gems installed by Rubygems/Bundler end up in a big mess.

**Comment by nyarly** [comment]
The only ever problem I've had managing Rubies on Gentoo was writing a script to set up the symlinks such that chruby could switch between them. And the *only* gem I've had anything like consistent or outsized issues getting to build against a Portage installed Ruby from Bundler was nokogumbo.

In other words: we have a deployment environment that works for us: Portage rubies and Bundler gems. I'm sorry if that caused you problems in the past, but the change introduced in 1.4.7 breaks that situation without recourse apart from "change your deployment strategy."

As far as I can tell, there isn't a way I can pass a switch via the gem/bundler install process that will fix the compile issue that the extconf.rb patch rolls back - maybe the solution would be to add a switch that the extconf itself checks for (rather than doing any kind of platform detection) and leave the fix in place there.

**Comment by rubys** [comment]
> but the change introduced in 1.4.7 

I'm not a Gentoo user, but my admittedly limited understanding is that a more proper description would be "the hack reverted in 1.4.7".  There seems to be a general agreement that this should be fixed "upstream", that it hasn't been fixed upstream, and nobody knows of a plan for said upstream fix.

Is that an accurate description?

The hack itself looks for a file that is guaranteed to exist on all Gentoo installations, and if found, does some things that fixes the problem for some and causes a problem for others.

Perhaps the right solution would be to reintroduce this code, but looking for a file that is unlikely to be on ANYBODY's machine, but people who have this problem can create and forget.

**Comment by svoop** [comment]
Not quite. It has been fixed upstream in the nokogumbo ebuild, but that fix is never applied for @nyarly  since he installs nokogumbo thru Rubygems/Bundler.

> Perhaps the right solution would be to reintroduce this code, but looking for a file that is unlikely to be on ANYBODY's machine, but people who have this problem can create and forget.

That would work. Another approach might be build options which can be persisted in Bundler's config, see BUILD OPTIONS:

http://bundler.io/v1.3/man/bundle-config.1.html

Other possible solutions (untested): Install the [nokogumbo ebuild](https://packages.gentoo.org/packages/dev-ruby/nokogumbo) before you deploy so Bundler doesn't have to.

(A lil background: Gentoo maintainers see Portage as the "one and only package manager on Gentoo" and therefore suggest you install Rubies and gems with it. This is of course nonsense in Bundler enabled Rubyland.)

**Comment by nyarly** [comment]
The hack was to explicitly add LD flags to find Nokogiri's shared library. I'm not sure why this would be necessary in the Rubygems domain, but there it is. So it's not "a file that should be on every install" but "a file that should already exist where Nokogumbo is installed" since it depends on Nokogiri already.

"Upstream" doesn't help in a Bundler deploy, since the idea would be that the distro packaging of Nokogumbo would include the patch. @svoop is right that there's a chauvinism about Portage as the authoritative package manager, but that's a tale as old as time in Linux distros (and among ops folks in general.)

A solution that let `bundle config build.nokogumbo ...` work would be ideal, but without some support for it I don't see how it'd work - while adding `-l:nokogiri.so` isn't hard, the nokogiri ext directory isn't something that (I think) I can perfectly predict over time.

The question that lingers for me is: goes nokogumbo statically link against `nokogiri.so`? I'd think that bundler/rubygems would manage the LDPATH to make sure it was available at runtime, so why do we need `nokogiri.so` at build time?

**Comment by rubys** [comment]
> The hack was to explicitly add LD flags to find Nokogiri's shared library. I'm not sure why this would be necessary in the Rubygems domain, but there it is.

It shouldn't be necessary. It isn't necessary on OS/X or Ubuntu.  And prior fixes that added that flag have broken OS/X.  Some history can be found here: https://github.com/rubys/nokogumbo/issues/4.  In that thread there may be a workaround: https://github.com/rubys/nokogumbo/issues/4#issuecomment-45164756

I'm not willing to accept a patch that breaks OS/X or Ubuntu, but I am willing to accept a patch that exposes a configuration choice that can be used by those who are affected by whatever the underlying bug is.

**Comment by nyarly** [comment]
Looking into root causes on Gentoo. Could I see a gist of the Makefile and it's output on OS X or Ubuntu?

**Comment by rubys** [comment]
Slightly more than you asked for:

https://intertwingly.net/tmp/macosx-nokogumbo-1.4.7.tgz
https://intertwingly.net/tmp/ubuntu-nokogumbo-1.4.7.tgz

If this is a problem, let me know and I'll go back and extract specific files.

**Comment by nyarly** [comment]
That was perfect. While the workaround above doesn't quite work, the comparison to the ubuntu Makefile leads me to:

`gem install nokogumbo -- --with-ldflags=-Wl,--undefined` which works great. I think that's as good as it's going to get - is there a good place to doc this flag?

**Comment by rubys** [comment]
Sigh.  https://github.com/rubys/nokogumbo/issues/61

**Comment by rubys** [comment]
I've reverted this change as it breaks Heroku

**Comment by winny-** [comment]
Greetings - might it be prudent to reopen this if the fixes were reverted?

**Comment by stevecheckoway** [comment]
@winny-, is Nokogumbo currently broken somewhere? We test Gentoo as part of our continuous integration testing. The [most recent build](https://travis-ci.org/rubys/nokogumbo/jobs/481032069) is passing.

**Comment by winny-** [comment]
@stevecheckoway Apologies - I neglected to ensure a ruby project I was working with had a newer version of nokogumbo. It builds successfully with 2.0.1 (was using 1.5.0 which is pretty old).

Everything works, sorry for the distraction.

**Comment by stevecheckoway** [comment]
@winny-, No worries, glad everything is working!
