### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by craig-day** [rubys/nokogumbo#43]
It looks like the Nokogumbo parser is messing with the encoding more than it should be.  The space escape character `\b` is getting converted to an unknown char (�) somewhere along the line that it isn't in nokogiri.  I'm not sure if this is specific to this library, or maybe the gumbo parser in general, but I'm starting here for now. 

```
# Nokogiri::HTML
> Nokogiri::HTML.parse("<p>※送信締切　2016年5月10日（\b火曜日）AM10：00\n</p>")
=> #<Nokogiri::HTML::Document:0x3ff74eae8758 name="document" children=[#<Nokogiri::XML::DTD:0x3ff74eae8438 name="html">, #<Nokogiri::XML::Element:0x3ff74eae81b8 name="html" children=[#<Nokogiri::XML::Element:0x3ff74eae7fb0 name="body" children=[#<Nokogiri::XML::Element:0x3ff74eae7dd0 name="p" children=[#<Nokogiri::XML::Text:0x3ff74eae7bf0 "※送信締切　2016年5月10日（火曜日）AM10：00\n">]>]>]>]>
```

Notice in the last text element, the content is fine
`#<Nokogiri::XML::Text:0x3ff74eae7bf0 "※送信締切　2016年5月10日（火曜日）AM10：00\n">`

```
# Nokogiri::HTML5
> Nokogiri::HTML5.parse("<p>※送信締切　2016年5月10日（\b火曜日）AM10：00\n</p>")
=> #<Nokogiri::HTML::Document:0x3ff74eae11c4 name="document" children=[#<Nokogiri::XML::Element:0x3ff74eae0ea4 name="html" children=[#<Nokogiri::XML::Element:0x3ff74eae0cc4 name="head">, #<Nokogiri::XML::Element:0x3ff74eae0af8 name="body" children=[#<Nokogiri::XML::Element:0x3ff74eae0918 name="p" children=[#<Nokogiri::XML::Text:0x3ff74eae0698 "※送信締切　2016年5月10日（�火曜日）AM10：00\n">]>]>]>]>
```

Notice in the last text element, the content is corrupt
`#<Nokogiri::XML::Text:0x3ff74eae0698 "※送信締切　2016年5月10日（�火曜日）AM10：00\n">`

**Comment by stevecheckoway** [comment]
I believe `HTML5.parse`'s behavior is both intended and correct here. The [p element](https://html.spec.whatwg.org/#the-p-element)'s content model is [phrasing content](https://html.spec.whatwg.org/#phrasing-content-2) and the text nodes (which is what this is) are restricted to be "scalar values, excluding noncharacters, and controls other than ASCII whitespace."

Continuing, [controls](https://infra.spec.whatwg.org/#control) include [C0 controls](https://infra.spec.whatwg.org/#c0-control) which include U+0008 which is what `\b` is. Thus, I believe the implementation is correct.

As for intended behavior, if you look in Gumbo's `utf8.c`, it contains the function

```c
// Returns true if this Unicode code point is in the list of characters
// forbidden by the HTML5 spec, such as undefined control chars.
bool utf8_is_invalid_code_point(int c) {
  return (c >= 0x1 && c <= 0x8) || c == 0xB || (c >= 0xE && c <= 0x1F) ||
         (c >= 0x7F && c <= 0x9F) || (c >= 0xFDD0 && c <= 0xFDEF) ||
         ((c & 0xFFFF) == 0xFFFE) || ((c & 0xFFFF) == 0xFFFF);
}
```
You can see that `\b` is invalid. (Although the function name is misleading since it's a valid unicode code point.)

**Comment by stevecheckoway** [comment]
In fact, if you examine the errors, you can see that it's not valid. (Although the error message is not great and the carrot points to the wrong location):

``` ruby
> x = Nokogiri::HTML5.parse("<!DOCTYPE html>\n<p>※送信締切　2016年5月10日（\b火曜日）AM10：00\n</p>")
> x.errors[0]
=> #<Nokogiri::XML::SyntaxError: @2:21: Invalid UTF8 character 0x8.
<p>※送信締切　2016年5月10日 火曜日）AM10：00
                    ^>
```
The shell appears to have acted on the backspace character.

This is easier to see with a smaller example.

``` ruby
> Nokogiri::HTML5.parse("<!DOCTYPE html>\nAAA\bBBB").errors[0]
=> #<Nokogiri::XML::SyntaxError: @2:4: Invalid UTF8 character 0x8.
AABBB
   ^>
```

**Comment by craig-day** [comment]
Awesome! Thanks for all of the detail @stevecheckoway. Feel free to close this if you believe everything is working as intended. I'll look into my specific case another way.
